[versie]
path = "~/p/versie"
repo = "git@github.com:Lyr-7d1h/versie.git"
update = true

[creagen-editor]
path = "~/p/creagen-editor"
repo = "git@github.com:Lyr-7d1h/creagen-editor.git"
update = true

[creagen-generations]
path = "~/p/creagen-generations"
repo = "git@github.com:Lyr-7d1h/creagen-generations.git"
update = true

[creagen-deployment]
path = "~/p/creagen-deployment"
repo = "git@github.com:Lyr-7d1h/creagen-cloudflare.git"
update = true

[creagen]
path = "~/p/creagen"
repo = "git@github.com:Lyr-7d1h/creagen.git"
execnow = "code ~/p/creagen ~/p/creagen-editor ~/p/creagen-generations ~/p/creagen-deployment ~/p/versie"
update= true

[[creagen.windows]]
name = "versie"
cwd = "~/p/versie"
[[creagen.windows.panes]]
exec = ["npm i", "npm run build:watch"]
[[creagen.windows.panes]]
exec = "watch --interval=1 --color --no-title \"jj --color=always -r 'all()'\""
[[creagen.windows.panes]]
split = "horizontal"
exec = ""

[[creagen.windows]]
name = "creagen"
[[creagen.windows.panes]]
exec = ["npm i", "npm run watch"]
[[creagen.windows.panes]]
exec = "watch --interval=1 --color --no-title \"jj --color=always -r 'all()'\""
[[creagen.windows.panes]]
split = "horizontal"
exec = ""

[[creagen.windows]]
name = "creagen-editor"
cwd = "~/p/creagen-editor"
[[creagen.windows.panes]]
split = "horizontal"
exec = [
	"npm i",
	"CREAGEN_EDITOR_CONTROLLER_URL=http://localhost:8787 npm start",
]
[[creagen.windows.panes]]
exec = "watch --interval=1 --color --no-title \"jj --color=always -r 'all()'\""
[[creagen.windows.panes]]
split = "horizontal"
exec = ""

[[creagen.windows]]
cwd = "~/p/creagen-deployment"
name = "deployment"
[[creagen.windows.panes]]
cwd = "~/p/creagen-deployment/controller"
exec = ["cd controller", "npm i", "npm start"]
[[creagen.windows.panes]]
exec = ""
