[genart]
path = "~/p/genart"
repo = "git@github.com:Lyr-7D1h/genart.git"
update = true
execnow = "code -r ."
[[genart.windows]]
name = "reload"
vsplit = false
[[genart.windows.panes]]
cwd = "genart"
exec = "npm i && npm run watch"
[[genart.windows.panes]]
cwd = "genart-editor"
exec = "npm i && npm start"
