[font]
size = 13.0

[font.normal]
family = "Ubuntu Mono Nerd Font"

[window]
opacity = 1.0

[window.padding]
x = 10
y = 10

[[hints.enabled]]
# HACK: firefox needs WAYLAND_DISPLAY set
command = "/home/lyr/.config/alacritty/firefox-wayland" 
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
