[colors.primary]
background = '#FFFFFF'
foreground = '#1F1F1F'

[colors.cursor]
text = "#FFFFFF"
cursor = "#264F78"

[colors.normal]
black = "#1F1F1F"
red = "#F44747"
green = "#6A9955"
yellow = "#795E26"
blue = "#007ACC"
magenta = "#C586C0"
cyan = "#e34ffe"
white = "#D4D4D4"

[colors.bright]
black = "#808080"
