"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Lyr"
email = "lyr-7d1h@pm.me"

[ui]
default-command = "log"
pager = "delta"
diff-formatter = ":git"

[templates]
# show diff in commands like 'describe'
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
